In [1]:
import pandas as pd

In [2]:
emails = ["anita.dev@corp.com", "rahul.hr@corp.com", "sales.team@corp.com",
          "meera.data@corp.com", "vikram.hr@corp.in", "priya.ops@corp.com"]

email_series = pd.Series(emails, name="emails")
email_series

0     anita.dev@corp.com
1      rahul.hr@corp.com
2    sales.team@corp.com
3    meera.data@corp.com
4      vikram.hr@corp.in
5     priya.ops@corp.com
Name: emails, dtype: str

In [3]:
codes = ["ENG-101", "MKT-205", "SAL-330", "HR-118", "ENG-202", "OPS-404"]

code_series = pd.Series(codes, name="codes")
code_series

0    ENG-101
1    MKT-205
2    SAL-330
3     HR-118
4    ENG-202
5    OPS-404
Name: codes, dtype: str

In [4]:
email_series.str.contains("hr")

0    False
1     True
2    False
3    False
4     True
5    False
Name: emails, dtype: bool

In [5]:
# a bool series can be used to filter straight away
email_series[email_series.str.contains("hr")]

1    rahul.hr@corp.com
4    vikram.hr@corp.in
Name: emails, dtype: str

In [8]:
email_series[email_series.str.startswith("anita")]

0    anita.dev@corp.com
Name: emails, dtype: str

In [9]:
email_series.str.endswith(".com")

0     True
1     True
2     True
3     True
4    False
5     True
Name: emails, dtype: bool

In [10]:
code_series.str.slice(0, 3)

0    ENG
1    MKT
2    SAL
3    HR-
4    ENG
5    OPS
Name: codes, dtype: str

In [11]:
code_series.str.slice(-3)

0    101
1    205
2    330
3    118
4    202
5    404
Name: codes, dtype: str

In [12]:
# without expand each row keeps a list of the pieces
code_series.str.split("-")

0    [ENG, 101]
1    [MKT, 205]
2    [SAL, 330]
3     [HR, 118]
4    [ENG, 202]
5    [OPS, 404]
Name: codes, dtype: object

In [13]:
# with expand the pieces become separate columns
code_series.str.split("-", expand=True)

     0    1
0  ENG  101
1  MKT  205
2  SAL  330
3   HR  118
4  ENG  202
5  OPS  404

In [14]:
email_series.str.split("@", expand=True)

            0         1
0   anita.dev  corp.com
1    rahul.hr  corp.com
2  sales.team  corp.com
3  meera.data  corp.com
4   vikram.hr   corp.in
5   priya.ops  corp.com

In [15]:
email_series.str.replace("corp", "company")

0     anita.dev@company.com
1      rahul.hr@company.com
2    sales.team@company.com
3    meera.data@company.com
4      vikram.hr@company.in
5     priya.ops@company.com
Name: emails, dtype: str

In [16]:
email_series.str.count("a")

0    2
1    1
2    2
3    3
4    1
5    1
Name: emails, dtype: int64